#!/bin/sh
# 首次启动自动配置：开启 Packet Steering（多队列网卡软中断均衡）
uci -q get network.globals.packet_steering > /dev/null || {
    uci set network.globals='globals'
    uci set network.globals.packet_steering=1
    uci commit network
}

# 时区设为 Asia/Shanghai
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system

# Luci 诊断目标改为国内站点
uci set luci.diag.dns='www.baidu.com'
uci set luci.diag.ping='www.baidu.com'
uci set luci.diag.route='www.baidu.com'
uci commit luci

# nginx：删除 _redirect2ssl 强制跳转，_lan 只监听 80 端口（HTTP）
uci set nginx.global.uci_enable='true'
uci del nginx._lan 2>/dev/null
uci del nginx._redirect2ssl 2>/dev/null
uci add nginx server
uci rename nginx.@server[0]='_lan'
uci set nginx._lan.server_name='_lan'
uci add_list nginx._lan.listen='80 default_server'
uci add_list nginx._lan.listen='[::]:80 default_server'
uci add_list nginx._lan.include='conf.d/*.locations'
uci set nginx._lan.access_log='off; # logd openwrt'
uci commit nginx
service nginx restart

exit 0
