name: Build x86/64

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'OpenWrt 版本分支'
        required: false
        default: 'main'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      target: x86_64
      version: ${{ inputs.version || 'main' }}
